name: WakaTime Stats ⏱

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:    

jobs:
  wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Generate WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_OS: "false"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_TIMEZONE: "false"
          SHOW_LOC_CHART: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LINES_OF_CODE: "false"
          SHOW_COMMIT: "false"
          SHOW_UPDATED_DATE: "true"
          SHOW_TOTAL_CODE_TIME: "false"

          COMMIT_MESSAGE: "📊 Updated WakaTime Stats"
          COMMIT_USERNAME: "waka-bot"
          COMMIT_EMAIL: "waka-bot@users.noreply.github.com"
          PUSH_BRANCH_NAME: "RTX"
